# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Job',
        ),
    ]
