# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190303_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default="It doesn't matter"),
            preserve_default=False,
        ),
    ]
